"""Build an offline copy of the real app with browser checks in its closure."""
from pathlib import Path
import re, subprocess, tempfile, sys
loading="--loading" in sys.argv
root=Path(__file__).resolve().parents[1]
s=(root/'encrypted-notes.html').read_text()
s=re.sub(r'<script src="[^"]+"></script>','',s)
s=s.replace('<link rel="stylesheet" href="/editor-features.css">','<style>'+ (root/'editor-features.css').read_text()+'</style>')
s=s.replace('<link rel="stylesheet" href="/workspace.css">','<style>'+ (root/'workspace.css').read_text()+'</style>')
if loading: s=s.replace('  const supa=','  let supa=',1)
pos=s.index('  (async()=>{',s.index("  $('#date-line').textContent="))
end=s.index('\n})();',pos)
s=s[:pos]+(root/('tests/note-loading-browser-tests.js' if loading else 'tests/editor-browser-tests.js')).read_text().replace('</script>', '<\\/script>')+s[end:]
s=s.replace('<body>','<body><pre id="test-results">RUNNING</pre>',1)
s=s.replace('<script>','<script>'+ (root/'device-lock.js').read_text()+'\n'+(root/'editor-features.js').read_text()+'\n'+(root/'workspace.js').read_text()+'</script><script>',1)
with tempfile.TemporaryDirectory(prefix='notes-editor-tests-') as d:
    p=Path(d)/'test.html';p.write_text(s)
    from playwright.sync_api import sync_playwright
    with sync_playwright() as pw:
        browser=pw.chromium.launch(executable_path='/usr/bin/google-chrome',headless=True,args=['--no-sandbox','--allow-file-access-from-files'])
        page=browser.new_page(viewport={'width':1280,'height':900},locale='en-GB' if '--24h' in sys.argv else 'en-US')
        errors=[]
        page.on('pageerror',lambda e: errors.append(str(e)))
        dialog_answers=[]
        def answer_dialog(dialog):
            if dialog.type=='prompt' and dialog_answers:
                dialog.accept(dialog_answers.pop(0))
            elif dialog.type=='confirm':
                dialog.accept()
            else:
                dialog.dismiss()
        page.on('dialog',answer_dialog)
        page.goto(p.as_uri(),wait_until='domcontentloaded')
        try:
            page.wait_for_function("document.querySelector('#test-results').textContent !== 'RUNNING'",timeout=20000)
        except Exception:
            print('Browser errors:',errors)
        result=page.locator('#test-results').inner_text()
        print(result)
        Path('/tmp/notes-editor-browser-results.html').write_text(page.content())
        if result.startswith('PASS') and not loading:
            page.locator('#test-results').evaluate('(el)=>el.hidden=true')
            page.locator('#new-note').click()
            page.wait_for_function("document.querySelectorAll('#editor > .block').length === 1")
            editable=page.locator('#editor .block-content').first
            editable.fill('Hello world')
            def select_first(start,end):
                page.evaluate("([a,b])=>{const e=document.querySelector('#editor .block-content');e.focus();const r=document.createRange();const point=offset=>{const walk=document.createTreeWalker(e,NodeFilter.SHOW_TEXT);let n,last;while(n=walk.nextNode()){last=n;if(offset<=n.length)return [n,offset];offset-=n.length}return [last,last.length]};r.setStart(...point(a));r.setEnd(...point(b));const s=getSelection();s.removeAllRanges();s.addRange(r)}",[start,end])
            select_first(0,5)
            page.keyboard.press('Control+i')
            assert editable.locator('i,em').inner_text()=='Hello','Native italic shortcut'
            page.keyboard.press('Control+z')
            assert editable.locator('i,em').count()==0,'Undo native formatting'
            page.keyboard.press('Control+Shift+z')
            assert editable.locator('i,em').count()==1,'Redo native formatting'
            editable.fill('Toolbar')
            select_first(0,7)
            page.locator('.selection-tools').wait_for(state='visible')
            page.locator('.selection-tools').get_by_role('button',name='Underline · Ctrl+U',exact=True).click()
            assert editable.locator('u').count()==1,'Selection toolbar underline'
            page.locator('.selection-tools select[aria-label=Color]').select_option('#b84b4b')
            assert editable.evaluate("e=>[e,...e.querySelectorAll('*')].some(n=>getComputedStyle(n).color==='rgb(184, 75, 75)')"),'Selection text color'
            page.locator('.selection-tools select[aria-label=Highlight]').select_option('#fff0a5')
            assert 'rgb(255, 240, 165)' in editable.inner_html(),'Selection highlight'
            page.keyboard.press('Control+z')
            assert 'rgb(255, 240, 165)' not in editable.inner_html(),'Undo highlight'
            editable.fill('AlphaBeta')
            select_first(5,5)
            page.keyboard.press('Enter')
            assert page.locator('#editor > .block').count()==2,'Paragraph splits at cursor'
            assert page.locator('#editor .block-content').nth(0).inner_text()=='Alpha'
            assert page.locator('#editor .block-content').nth(1).inner_text()=='Beta'
            page.locator('#editor .block-content').nth(1).fill('/toggle')
            page.locator('.command-menu').wait_for(state='visible')
            page.keyboard.press('Enter')
            assert page.locator('#editor > [data-type=toggle]').count()==1,'Real slash menu typing'
            page.locator('#editor [data-type=toggle] .toggle-title .block-content').fill('Details')
            page.keyboard.press('Enter')
            page.keyboard.type('Inside toggle')
            assert page.locator('#editor .toggle-body').inner_text()=='Inside toggle'
            page.locator('.floating-tools [data-insert=text]').click()
            page.locator('.command-menu button').filter(has_text='Rows and columns').click()
            assert page.locator('#editor .note-table').count()==1
            page.evaluate('scrollTo(0,0)')
            page.screenshot(path='/tmp/notes-editor-desktop.png',full_page=True)
            page.set_viewport_size({'width':390,'height':844})
            assert page.locator('.subtitle-row').bounding_box()['width'] <= 390
            assert page.locator('.editor-actions').count()==0
            page.screenshot(path='/tmp/notes-editor-mobile.png',full_page=True)
            page.locator('.floating-tools [data-insert=text]').click()
            assert page.locator('.command-menu').bounding_box()['x'] >= 0
            page.locator('.command-menu').get_by_role('button',name='Callout').click()
            assert page.locator('#editor [data-type=callout]').count()==1
            # Real workspace navigation and lifecycle controls on mobile.
            page.locator('#mobile-menu').click()
            dialog_answers.append('Daily')
            page.locator('#new-folder').click()
            page.locator('.home-heading h1').filter(has_text='Daily').wait_for()
            page.locator('#home-new-note').click()
            page.wait_for_function("document.querySelector('.folder-children .sidebar-page-row') !== null")
            assert page.locator('.workspace-note-controls').count()==0
            page.locator('#editor .block-content').first.fill('Work note')
            page.locator('#mobile-menu').click()
            page.locator('.folder-children .page-more').click()
            page.locator('.sidebar-page-menu').get_by_role('button',name='Rename',exact=True).click()
            page.get_by_role('textbox',name='Note name').fill('Renamed work')
            page.locator('.sidebar-page-menu').get_by_role('button',name='Save name').click()
            page.locator('#note-title').filter(has_text='Renamed work').wait_for()
            page.locator('.folder-children .page-more').click()
            page.locator('.sidebar-page-menu').get_by_role('button',name='Archive',exact=True).click()
            page.locator('#archive-notes').click()
            assert page.locator('#recent-grid .recent-card').count()==1
            page.locator('#recent-grid .card-actions').get_by_role('button',name='Unarchive',exact=True).click()
            page.wait_for_function("document.querySelectorAll('#recent-grid .recent-card').length === 0")
            page.locator('#mobile-menu').click()
            page.locator('#all-notes').click()
            page.locator('#mobile-menu').click()
            page.locator('.folder-open').filter(has_text='Daily').click()
            page.locator('#mobile-menu').click()
            page.locator('.folder-children .page-more').click()
            page.locator('.sidebar-page-menu').get_by_role('button',name='Move to recycle bin',exact=True).click()
            page.locator('#trash-notes').click()
            page.locator('.home-heading h1').filter(has_text='Recycle bin').wait_for()
            assert page.locator('#recent-grid .recent-card').count()==1
            page.locator('#recent-grid .card-actions').get_by_role('button',name='Restore',exact=True).click()
            page.wait_for_function("document.querySelectorAll('#recent-grid .recent-card').length === 0")
            page.locator('#mobile-menu').click()
            page.locator('#all-notes').click()
            page.locator('#mobile-menu').click()
            page.locator('.folder-open').filter(has_text='Daily').click()
            assert page.locator('#recent-grid .recent-card').count()==1
            page.locator('#recent-grid .recent-card').click()
            assert not page.locator('#editor').evaluate('(e)=>e.inert')
            page.locator('#mobile-menu').click()
            page.locator('.sidebar-page-row').filter(has=page.locator('.note-row.current')).get_by_role('button',name='New subpage in Renamed work',exact=True).click()
            page.locator('#note-title').filter(has_text='Untitled').wait_for()
            content=page.locator('#editor .block-content').first
            content.fill('@Renamed')
            page.locator('.page-mention-menu').wait_for(state='visible')
            page.keyboard.press('Enter')
            assert content.locator('a[data-page-id]').inner_text()=='Renamed work'
            content.locator('a[data-page-id]').click()
            page.locator('#note-title').filter(has_text='Renamed work').wait_for()
            assert 'Backlinks' in page.locator('.page-relations').inner_text()
            print('PASS real subpage creation and keyboard page mentions')
            page.locator('#editor .block-content').first.fill('@today')
            page.locator('.page-mention-menu').wait_for(state='visible')
            page.keyboard.press('Enter')
            assert page.locator('#editor [data-date-mention]').count()==1
            page.locator('#mobile-menu').click()
            page.locator('#threads-notes').click()
            dialog_answers.append('Daily movement')
            page.locator('#home-new-note').click()
            page.locator('.threads-table').get_by_role('button',name='Daily movement',exact=True).wait_for()
            page.get_by_label('Thread month',exact=True).fill('2026-09')
            page.wait_for_function("document.querySelectorAll('.threads-table thead th').length===31")
            page.get_by_role('checkbox',name='Daily movement · 2026-09-25',exact=True).check()
            page.get_by_role('checkbox',name='Daily movement · 2026-09-25',exact=True).wait_for()
            assert page.get_by_role('checkbox',name='Daily movement · 2026-09-25',exact=True).is_checked()
            page.get_by_role('checkbox',name='Daily movement · 2026-09-25',exact=True).uncheck()
            assert not page.get_by_role('checkbox',name='Daily movement · 2026-09-25',exact=True).is_checked()
            page.screenshot(path='/tmp/threads-mobile.png',full_page=True)
            page.set_viewport_size({'width':1440,'height':1000})
            page.screenshot(path='/tmp/threads-desktop.png',full_page=True)
            page.set_viewport_size({'width':390,'height':844})
            page.locator('.threads-table').get_by_role('button',name='Daily movement',exact=True).click()
            page.locator('#editor .block-content').first.fill('@newpage')
            page.locator('.page-mention-menu').get_by_role('option',name='Create subpage “New page”').wait_for()
            page.keyboard.press('Enter')
            page.locator('#editor a[data-page-id]').wait_for()
            assert page.locator('#note-title').inner_text()=='Daily movement'
            assert page.locator('.slash-hint').count()==0
            page.locator('#mobile-menu').click()
            page.locator('#threads-notes').click()
            dialog_answers.append('Second thread')
            page.locator('#home-new-note').click()
            page.get_by_role('button',name='Options for thread Second thread',exact=True).click()
            assert page.locator('.sidebar-page-menu').get_by_role('button',name='Move up',exact=True).count()==0
            assert page.locator('.sidebar-page-menu').get_by_role('button',name='Move down',exact=True).count()==0
            page.keyboard.press('Escape')
            handle=page.get_by_role('button',name='Reorder Second thread',exact=True)
            handle.focus()
            page.keyboard.press('Space')
            page.keyboard.press('ArrowUp')
            page.keyboard.press('Space')
            page.wait_for_function("document.querySelector('.threads-table tbody tr th').textContent.includes('Second thread')")
            page.get_by_role('button',name='Options for thread Second thread',exact=True).click()
            page.locator('.sidebar-page-menu').get_by_role('button',name='Delete thread',exact=True).click()
            page.get_by_role('button',name='Thread recycle bin',exact=True).click()
            page.get_by_role('button',name='Options for thread Second thread',exact=True).click()
            page.locator('.sidebar-page-menu').get_by_role('button',name='Restore thread',exact=True).click()
            page.get_by_role('button',name='Active threads',exact=True).click()
            page.locator('.threads-table').get_by_role('button',name='Second thread',exact=True).wait_for()
            page.set_viewport_size({'width':1440,'height':1000})
            source=page.get_by_role('button',name='Reorder Daily movement',exact=True).bounding_box()
            target=page.get_by_role('button',name='Reorder Second thread',exact=True).bounding_box()
            page.mouse.move(source['x']+source['width']/2,source['y']+source['height']/2)
            page.mouse.down()
            page.mouse.move(target['x']+target['width']/2,target['y']+5,steps=12)
            assert page.locator('.thread-drag-preview').is_visible()
            assert page.locator('.thread-drop-indicator').is_visible()
            page.mouse.up()
            assert page.locator('.thread-drag-preview').count()==0
            page.wait_for_function("document.querySelector('.threads-table tbody tr th').textContent.includes('Daily movement')")
            page.set_viewport_size({'width':390,'height':844})
            source=page.get_by_role('button',name='Reorder Second thread',exact=True).bounding_box()
            target=page.get_by_role('button',name='Reorder Daily movement',exact=True).bounding_box()
            cdp=page.context.new_cdp_session(page)
            cdp.send('Emulation.setTouchEmulationEnabled',{'enabled':True,'maxTouchPoints':1})
            cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':source['x']+15,'y':source['y']+15}]})
            cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':target['x']+15,'y':target['y']+3}]})
            assert page.locator('.thread-drag-preview').is_visible()
            page.screenshot(path='/tmp/threads-touch-drag.png',full_page=True)
            cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
            page.wait_for_function("document.querySelector('.threads-table tbody tr th').textContent.includes('Second thread')")
            assert page.locator('.thread-drag-preview').count()==0
            source=page.get_by_role('button',name='Reorder Second thread',exact=True).bounding_box()
            target=page.get_by_role('button',name='Reorder Daily movement',exact=True).bounding_box()
            cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':source['x']+15,'y':source['y']+15}]})
            cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':target['x']+15,'y':target['y']+target['height']+5}]})
            cdp.send('Input.dispatchTouchEvent',{'type':'touchCancel','touchPoints':[]})
            assert page.locator('.thread-drag-preview').count()==0
            assert 'Second thread' in page.locator('.threads-table tbody tr').first.inner_text()
            cdp.send('Emulation.setTouchEmulationEnabled',{'enabled':False})
            page.set_viewport_size({'width':1440,'height':1000})
            source=page.get_by_role('button',name='Reorder Second thread',exact=True).bounding_box()
            target=page.get_by_role('button',name='Reorder Daily movement',exact=True).bounding_box()
            page.mouse.move(source['x']+15,source['y']+15)
            page.mouse.down()
            page.mouse.move(target['x']+15,target['y']+target['height']+8,steps=12)
            page.mouse.up()
            page.wait_for_function("document.querySelector('.threads-table tbody tr th').textContent.includes('Daily movement')")
            print('PASS mouse, real touch and keyboard thread drag reordering; no move menu')
            print('PASS real date mention, monthly thread grid and checkbox interactions')
            page.set_viewport_size({'width':390,'height':700})
            cdp.send('Emulation.setTouchEmulationEnabled',{'enabled':True})
            page.evaluate("document.querySelector('#all-notes').click();document.querySelector('#new-note').click()")
            page.wait_for_function("!document.querySelector('#note-view').hidden")
            mobile_text=page.locator('#editor .block-content').first
            mobile_text.fill('@now');mobile_text.press('End');mobile_text.press('Backspace');mobile_text.press('w')
            option=page.get_by_role('option',name='@now',exact=True);option.wait_for(state='visible')
            rect=option.bounding_box();cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':rect['x']+30,'y':rect['y']+20}]});cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
            page.wait_for_function("document.querySelector('#editor [data-date-kind=now]')")
            assert page.locator('#editor [data-date-kind=now]').evaluate("el=>el.textContent===new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(el.dataset.dateMention))")
            mobile_text.evaluate("el=>{el.textContent='@now';el.focus();const r=document.createRange();r.selectNodeContents(el);r.collapse(false);getSelection().removeAllRanges();getSelection().addRange(r);el.dispatchEvent(new InputEvent('input',{bubbles:true}))}")
            assert mobile_text.evaluate("el=>!el.dispatchEvent(new InputEvent('beforeinput',{inputType:'insertParagraph',bubbles:true,cancelable:true}))")
            assert page.locator('#editor [data-date-kind=now]').count()==1
            assert page.evaluate("matchMedia('(pointer:coarse)').matches")
            assert mobile_text.evaluate("el=>!el.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))")
            assert mobile_text.evaluate("el=>{const r=document.createRange();r.selectNodeContents(el);getSelection().removeAllRanges();getSelection().addRange(r);return !getSelection().isCollapsed}")
            cdp.send('Emulation.setTouchEmulationEnabled',{'enabled':False})
            assert mobile_text.evaluate("el=>el.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))")
            page.set_viewport_size({'width':1440,'height':1000})
            page.evaluate('getSelection().removeAllRanges()');mobile_text.press('Escape')
            print('PASS mobile @now touch tap, virtual keyboard Enter, time-only label and context-menu suppression with text selection preserved')

            page.locator('#movies-notes').click()
            page.locator('#home-new-note').click()
            page.get_by_role('dialog',name='Add or edit movie').get_by_role('textbox',name='Movie name or link',exact=True).fill('https://youtu.be/M7lc1UVf-VE')
            page.get_by_role('textbox',name='Movie title',exact=True).fill('Mobile trailer')
            page.get_by_role('dialog',name='Add or edit movie').get_by_role('button',name='Add movie',exact=True).click()
            page.locator('.movie-title').filter(has_text='Mobile trailer').wait_for()
            page.get_by_role('button',name='Mark watched',exact=True).click()
            page.get_by_role('button',name='Watched',exact=True).click()
            page.locator('.movie-title').filter(has_text='Mobile trailer').wait_for()
            page.get_by_role('button',name='Move to watchlist',exact=True).click()
            page.get_by_role('button',name='Watchlist',exact=True).click()
            page.get_by_role('button',name='Play YouTube video').click()
            assert 'youtube-nocookie.com/embed/M7lc1UVf-VE' in page.locator('.movie-preview iframe').get_attribute('src')
            page.locator('#all-notes').click()
            assert 'Mobile trailer' not in page.locator('#recent-grid').inner_text()
            assert 'Mobile trailer' not in page.locator('#note-list').inner_text()
            page.locator('#movies-notes').click()
            page.locator('.movie-card').filter(has_text='Mobile trailer').get_by_role('button',name='Options for movie Mobile trailer',exact=True).click()
            page.get_by_role('button',name='Delete movie',exact=True).click()
            page.get_by_role('button',name='Movie recycle bin',exact=True).click()
            page.get_by_role('button',name='Restore movie',exact=True).click()
            page.get_by_role('button',name='Watchlist',exact=True).click()
            page.locator('.movie-title').filter(has_text='Mobile trailer').wait_for()
            page.screenshot(path='/tmp/movies-desktop.png',full_page=True)
            page.set_viewport_size({'width':390,'height':844})
            page.screenshot(path='/tmp/movies-mobile.png',full_page=True)
            print('PASS real movie add, watched, embed, separation and delete/restore')
            print('PASS real keyboard, selection formatting, undo and mobile layout checks')
        page.screenshot(path='/tmp/notes-editor-features.png',full_page=True)
        browser.close()
        raise SystemExit(0 if result.startswith('PASS') else 1)
